vich_uploader:
    db_driver: orm

    mappings:
        genre_images:
            uri_prefix: '%genre_images%'
            upload_destination: '%kernel.project_dir%/public%genre_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false
